# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "My awesome app"

  

  
end

platform :android do

  desc "move all the files to separate folder to upload them as artifacts"
  
  lane :move_files do

    version = File.read(File.join(File.dirname(__FILE__), '..', '..', 'pubspec.yaml')).match(/version: (.+)/)[1]
    buildCode = version.split('+')[0]

    buildNumber = ENV['CI_JOB_ID']

    if buildNumber == nil
        buildNumber = version.split('+')[1]
    end

    job = ENV['CI_JOB_ID']
    if job == nil
        job = '-1000'
    end


    buildNumber = buildNumber.slice(0, 8)

    file_prefix ="Academicmaster-#{git_branch}-#{buildCode}+#{buildNumber}".split("\n").first
    sh("cd .. && cd .. && mkdir -p build/artifacts")
    sh("mv ../../build/app/outputs/flutter-apk/app-release.apk ../../build/artifacts/#{file_prefix}.apk")
    sh("mv ../../build/app/outputs/flutter-apk/app-release.apk.sha1 ../../build/artifacts/#{file_prefix}.apk.sha1")
    sh("mv ../../build/app/outputs/apk/release/output-metadata.json ../../build/artifacts/output-metadata.json")
    sh("mv ../../build/app/outputs/bundle/release/app-release.aab ../../build/artifacts/#{file_prefix}.aab")

    dataToWrite = buildCode.split("\n").first + ',' + buildNumber.split("\n").first + ',' + job + ',' + sh("cd .. && cd .. && pwd | tr -d '\n'") + '/build/artifacts/' + file_prefix.split("\n").first + ".aab"
    sh("echo #{dataWrite} > ../../build/artifacts/metadata.dat")

    lane :increment_version do
      latest_release = firebase_app_distribution_get_latest_release(
        app: "1:301898640510:android:33692e9eea77178c18bc2f"
      )
      increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
    end
  
    lane :distribute do
        build_android_app(...)
        # build_android_app is a built-in fastlane action.
        release = firebase_app_distribution(
            app: "1:301898640510:android:33692e9eea77178c18bc2f",
            testers: "roberto.bolanos@it-strategy.com,",
            release_notes: "Test Release!"
        )
    end
  end
